server:
  port: 8082

spring:
  application:
    name: pedido-service-async

producto-service-async:
  url: http://localhost:8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true